import "./globals.css";
import Head from "next/head";
import NavbarLayout from "@/Component/NavbarLayout";
import FooterLayout from "@/Component/FooterLayout";


export const metadata = {
  title: "Figma to NextJS",
  description: "Generated by Hema",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');`}</style>
      </Head>
      <body>
        <div className="overflow-x-hidden">
          <NavbarLayout />
          <main>{children}</main>
          <FooterLayout />
        </div></body>
    </html>
  );
}
